### ISSUE TITLE
Move to trash

### ISSUE THREAD

**Issue by ABBAPOH** [ABBAPOH/andromeda#12]
Need to implement possibility to move files to trash instead of removing them

**Comment by jleclanche** [comment]
I have a Trash class in python which does the job nicely for xdg:

https://github.com/Adys/python-trash/blob/master/trash/backends/xdg.py

I also implemented a trash file system on top of QDir:
https://github.com/Adys/flipper/blob/master/flipper/backends/trashsystem.py

**Comment by ABBAPOH** [comment]
Hm, nice, however i already implemented trash in c++ : https://gitorious.org/andromeda/qtrash

**Comment by jleclanche** [comment]
Oh nice :) I'll have a look at it.

I don't suppose theres any chance you could write pyside bindings to it?

**Comment by ABBAPOH** [comment]
I don't know python:(

**Comment by ABBAPOH** [comment]
Seems done for now.
