### ISSUE TITLE
[RFE] allow to hide specified toolbars

### ISSUE THREAD

**Issue by pvanek** [ABBAPOH/andromeda#14]

**Comment by ABBAPOH** [comment]
TODO: Remove "hide action"(or add description?) to AddressBar toolbar
Add (?) "hide action" to BookmarksBar

**Comment by ABBAPOH** [comment]
Also need ability to hide/show menuBar

**Comment by ABBAPOH** [comment]
Can't hide main toolbar now. Added actions for hiding bookmarks toolbar and menubar.
