### ISSUE TITLE
Improve the rename file widget

### ISSUE THREAD

**Issue by jleclanche** [ABBAPOH/andromeda#30]
Renaming a file should look a lot better, and only select up to the file extension by default.

**Comment by ABBAPOH** [comment]
Resolved

**Comment by jleclanche** [comment]
Try renaming a file with a very long name, such as "index.html?id=9838b7032ea921f4792bec21a24c53c07078636d"; it still looks pretty terrible. Nice job on the extension, though.

**Comment by ABBAPOH** [comment]
Extension bus too in fact:) I need to integrate QMimeType to determine it correctly.
I will try to see what can be done to align line edit properly. Maybe i should use QTextEdit, like KDE does.

**Comment by ABBAPOH** [comment]
Ok, i made some investigations. QTextEdit should be used instead of QLineEdit. I should pass horizontal alignment flags from option to it.
The problem i couldn't solve - how to align text edit vertically. It always aligned at top, while it should be aligned in center.

**Comment by ABBAPOH** [comment]
Ok, that the best i can do.
