### ISSUE TITLE
Compiling breaks without qtwebkit

### ISSUE THREAD

**Issue by jleclanche** [ABBAPOH/andromeda#43]
% make -j1
[  0%] Built target qtlockedfile
[  2%] Built target qtsingleapplication
[ 12%] Built target extensionsystem
[ 13%] Built target plugineditor
[ 23%] Built target widgets
[ 43%] Built target guisystem
[ 52%] Built target io
[ 59%] Built target bookmarksplugin
[ 67%] Built target coreplugin
[ 85%] Built target filemanagerplugin
[ 87%] Built target helloworldplugin
[ 87%] Building CXX object src/plugins/webview/CMakeFiles/webviewplugin.dir/appearancesettings.cpp.o
/home/adys/src/chromic/andromeda/src/plugins/webview/appearancesettings.cpp:7:33: fatal error: QtWebKit/QWebSettings: No such file or directory  
compilation terminated.
make[2]: **\* [src/plugins/webview/CMakeFiles/webviewplugin.dir/appearancesettings.cpp.o] Error 1
make[1]: **\* [src/plugins/webview/CMakeFiles/webviewplugin.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ABBAPOH** [comment]
Webkit is a part of a qt sdk, so i don't see any problem why linux users can't install it too

**Comment by jleclanche** [comment]
andromeda shouldn't depend on it because of a plugin, though. If qtwebkit isn't found (cmakelists actually does detect that right now), it should avoid compiling it.

**Comment by ABBAPOH** [comment]
I agree that plugin should be disabled if an _external_ dependency is missing. But webkit is not an external dependency.
However i'll try to add check for it just to know how to detect that missing dependencies;)

**Comment by pvanek** [comment]
just add webkit as a REQUIRED part for FindQt4.cmake and it will fail configuration if it's not found

**Comment by ABBAPOH** [comment]
I prefer to disable plugin, not to fail whole compilation

**Comment by jleclanche** [comment]
Yes, that would be ideal.

**Comment by ABBAPOH** [comment]
Can someone test on a PC without webkit? (commit 0d8c19d), master branch.

**Comment by jleclanche** [comment]
Works, thanks!
