### ISSUE TITLE
Build failure on Linux for release 0.2

### ISSUE THREAD

**Issue by spaeps** [ABBAPOH/andromeda#44]
Hi,
I maintain andromeda on Arch Linux (AUR) [1] and i had to apply some patches in order to let latest release 0.2 build.
As you can see in the Arch build script [2], some source files are miss unistd.h to be included in

sed -i "60i#include <unistd.h>" src/shared/qtsingleapplication/qtlocalpeer.cpp
sed -i "18i#include <unistd.h>" src/libs/io/qdrivecontroller_linux.cpp
sed -i "12i#include <unistd.h>" src/libs/io/qtrash_linux.cpp

Also the GIT_REVISION cannot be set during the cmake configuration, since it is not dealing with a git source tree.
I temporally solved by setting it manually as it should be done:
sed -i "s/^get_git_revision.*/set( GIT_REVISION "52f1e6f0e9c10fda4c74443a151f5391638db5eb" )/" cmake/ProjectInfo.cmake

About the LIB_SUFFIX patch, not all distro use the /usr/lib64 path for storing 64 bit libraries,
probably the ability to define this variable globally for the cmake build would solve definitely.

Cheers

[1] https://aur.archlinux.org/packages.php?ID=55554
[2] https://aur.archlinux.org/packages/an/andromeda/PKGBUILD

**Comment by ABBAPOH** [comment]
Thanks for patches.

I'm not sure, but it seems you can specify when runnig cmkae using -DLIB_SUFFIX="" However, i'm not sure if this will work. If not, i have to detect that var is set, but empty.
But all Linuxes use /lib and /lib64 folders, aren't they?
