### ISSUE TITLE
andromeda . doesn't work

### ISSUE THREAD

**Issue by jleclanche** [ABBAPOH/andromeda#46]
Shows an empty tab without files.

**Comment by jleclanche** [comment]
Actually, any non-absolute path is treated as an url

**Comment by ABBAPOH** [comment]
Hm, seems QUrl::fromUserInput can't detect them

**Comment by jleclanche** [comment]
Makes sense since QUrls with a scheme cannot be relative.

You can try QDir.isRelativePath(path)

**Comment by ABBAPOH** [comment]
The problem is how to detect it's a file path, or an url address?
folder google.com/ looks same as http://google.com :(

**Comment by jleclanche** [comment]
Check if it exists first. If it does, _always_ assume file.

**Comment by ABBAPOH** [comment]
Try now (master)

**Comment by jleclanche** [comment]
Works.
