### ISSUE TITLE
Compilation failure in qstandardpaths_unix.cpp

### ISSUE THREAD

**Issue by jleclanche** [ABBAPOH/andromeda#47]
[ 44%] Building CXX object src/libs/io/CMakeFiles/io.dir/inqt5/qstandardpaths_unix.cpp.o  
/home/adys/src/chromic/andromeda/src/libs/io/inqt5/qstandardpaths_unix.cpp: In static member function 'static QString QStandardPaths::writableLocation(QStandardPaths::StandardLocation)':  
/home/adys/src/chromic/andromeda/src/libs/io/inqt5/qstandardpaths_unix.cpp:100:37: error: 'geteuid' was not declared in this scope
make[2]: **\* [src/libs/io/CMakeFiles/io.dir/inqt5/qstandardpaths_unix.cpp.o] Error 1
make[1]: **\* [src/libs/io/CMakeFiles/io.dir/all] Error 2

**Comment by ABBAPOH** [comment]
Try now

**Comment by jleclanche** [comment]
Fixed
