### ISSUE TITLE
Implement cut & paste

### ISSUE THREAD

**Issue by jleclanche** [ABBAPOH/andromeda#48]
Ctrl+X should cut to move.

**Comment by ABBAPOH** [comment]
It's almost impossible to implement in a cross-platfom way (i need support other FMs like Explorer or Dolphin and mime data should tell both programs to move file instead of copying - i don't know how to do it)

I'll add a workaround used in Apple Finder - "copy & paste-move" (Ctrl+C, Ctrl+Shift+V)

**Comment by jleclanche** [comment]
It at least needs to work within andromeda itself. Supporting other FMs is an extra feature.

**Comment by ABBAPOH** [comment]
Incorrect. Typical usecase - cut/paste to desktop.

**Comment by jleclanche** [comment]
It's still an extra feature compared to getting it to work within andromeda itself. Typical usecase: cut/paste to a different folder.
Would be nice to have that at least.

**Comment by ABBAPOH** [comment]
If you cut file and andromeda and it will work within user will expect that if he cuts file and pastes it to desktop, it will be moved. User will be confused if not - he doesn't see difference between andromeda, other FM or a desktop folder. He will see a bug and it's hard to explain to user why sometimes cut paste work and why sometimes doesn't.

**Comment by jleclanche** [comment]
Uhh... personally, andromeda is completely unusable without copy/paste support.

**Comment by ABBAPOH** [comment]
Add "Move here" action instead of "Cut"
Maybe one day i will implement "Cut"
