### ISSUE TITLE
Compile without imageviewer

### ISSUE THREAD

**Issue by jleclanche** [ABBAPOH/andromeda#66]
Is there a way to do that? cmake -L doesn't list one.

**Comment by ABBAPOH** [comment]
No, currently there's no option for that. Should i add it? Should i also disable image view plugin too or only app?

**Comment by jleclanche** [comment]
Yes, please add an option for it; I have my own image viewer :)

You should also be allowed to disable image view plugin separately, imo.

**Comment by ABBAPOH** [comment]
Btw, can i view you source?:) I want to have pure qt imageviewer, however my implementation has wrong architecture (it was just a test of animations and 3d-transformations). So it needs complete rewriting. Or an option to use other viewer (however, i didn't find any viewer with good architecture).

**Comment by jleclanche** [comment]
I actually use feh: http://feh.finalrewind.org/

It only depends on X11 and imlib2.

**Comment by ABBAPOH** [comment]
X11 dependency is quite huge one - i can't use it on windows/mac:(

**Comment by jleclanche** [comment]
Oh :/ I haven't looked at the code but I'm sure it's not too bad, could be clipped out for a Qt-based one.

**Comment by ABBAPOH** [comment]
Also it is c-based and can't use Qt features (like imageformats plugins)...

**Comment by jleclanche** [comment]
As far as qt-based ones go, I found qiviewer a while back but the code was atrocious.

**Comment by ABBAPOH** [comment]
Same architecture as i have, which is wrong:) Anyway, i thought it's not developed anymore, however last commit was in october, maybe it's author can be interested in cooperation... I'll try to contact him:)

**Comment by jleclanche** [comment]
I still have the https://github.com/qtdesktop organization if you want to move those apps there.

**Comment by ABBAPOH** [comment]
Why it's empty?:(

**Comment by jleclanche** [comment]
Sorry it's actually https://github.com/qtdesktop

**Comment by jleclanche** [comment]
It was a project to have collaboration on Qt apps in a similar environment as KDE has. There were quite a few people interested but it never went really far and I didn't ping back on it.

**Comment by ABBAPOH** [comment]
I think, a lot of people who are developing qt apps are either proprietary developers or kde devs:) In fact, Qt provides quite a few things - it doesn't have archive support, no virtual filesystem, until qt5 there were even no mimetypes. So people prefer to use frameworks that have those features - kde, for example.

**Comment by jleclanche** [comment]
is this possible now?

**Comment by ABBAPOH** [comment]
No, it's not possible right now; that requires changing project structure and migrating away from cmake.

**Comment by ABBAPOH** [comment]
Working on this issue.

**Comment by ABBAPOH** [comment]
Done. Imageviewer now lives in it' own repo (https://gitorious.org/andromeda/qimageviewer)
