### ISSUE TITLE
Do not limit File info window width

### ISSUE THREAD

**Issue by jleclanche** [ABBAPOH/andromeda#67]
User should be able to resize File info window in width as well.

**Comment by ABBAPOH** [comment]
I disagree. Why he should do that?

**Comment by jleclanche** [comment]
Main reason is because tabbed window managers are snapping the window to the folder window and resizing it, which is really annoying.

The other reason is because there's really no reason to limit it, imho. It's fine as default (although I think it should be a little larger), but limiting it is unnecessary.

**Comment by ABBAPOH** [comment]
The problem of resizable windows is that you need to store their size in settings. Otherwise, resizing is useless, imho. I was thinking about hardcoding height too:)
The main reason of small file info window is that you can open 2 windows one near another and compare them. But i can allow it, yes.

**Comment by jleclanche** [comment]
Yeah there's no need to store it in settings I think.
